#%RAML 1.0 DataType
description: This RAML specifies the request parameters i.e. country which will retrieve all the cities of that country in response.
type: object
properties:
  CountryName?:
    type: string
    description: Request param - Country Name 