#%RAML 1.0 DataType
description: Reusable error data types.

type: object
properties: 
  errorCode:
    type: string
    description: |
      Actual description of the error as per the error response code.
    required: false
  errorDescription:
    type: string
    description: |
      Actual description of the error as per the error response code.
    required: false